Repository roadrunner-server/otel, pull requests merged in 2024-10, with the labels that each got.

#65 feat: Add JSON schema
  schema.json
Labels: documentation

#64 feature: detect resources from environment variables when not set in config
  config.go
  plugin.go
Labels: enhancement

#66 chore: Adjust default naming logic for otel resources
  config.go
  go.mod
  go.sum
  schema.json
Labels: documentation, enhancement
